import type { BankQuestion } from "@/lib/curriculum/types";

export const BANK_QUESTIONS: BankQuestion[] = [
  {
    id: "q-num-001",
    prompt: "Simplify 12/18.",
    marks: 1,
    answer: "2/3",
    solution: "Divide numerator and denominator by 6: 12÷6=2, 18÷6=3, so 2/3.",
    skillIds: ["num.fractions"],
    topicId: "number",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Simplify"],
    commonMistakes: ["Dividing only the numerator"],
  },
  {
    id: "q-num-002",
    prompt: "Work out 3/4 + 2/5.",
    marks: 2,
    answer: "23/20|1.15|1 3/20",
    solution: "Common denominator 20: 15/20 + 8/20 = 23/20.",
    skillIds: ["num.fractions"],
    topicId: "number",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Work out"],
    commonMistakes: ["Adding denominators to get 5/9"],
  },
  {
    id: "q-num-003",
    prompt: "Increase £80 by 15%.",
    marks: 2,
    answer: "92|£92",
    solution: "Multiplier 1.15. 80 × 1.15 = 92.",
    skillIds: ["num.percentages"],
    topicId: "number",
    difficulty: 4,
    calculator: true,
    type: "short",
    commandWords: ["Increase"],
    commonMistakes: ["Finding 15% and forgetting to add it"],
  },
  {
    id: "q-num-004",
    prompt: "Share £120 in the ratio 2:3:7.",
    marks: 3,
    answer: "20:30:70|£20, £30, £70",
    solution: "Parts 2+3+7=12. One part = 120/12 = 10. Amounts 20, 30, 70.",
    skillIds: ["num.ratio", "rat.ratio"],
    topicId: "ratio",
    difficulty: 4,
    calculator: false,
    type: "structured",
    commandWords: ["Share"],
    commonMistakes: ["Dividing 120 by 2, 3 and 7 separately"],
  },
  {
    id: "q-num-005",
    prompt: "Write 0.00047 in standard form.",
    marks: 1,
    answer: "4.7 × 10^-4|4.7x10^-4",
    solution: "Move the point 4 places: 4.7 × 10^-4.",
    skillIds: ["num.standard-form"],
    topicId: "number",
    difficulty: 5,
    calculator: false,
    type: "short",
    commandWords: ["Write"],
    commonMistakes: ["Positive index", "4.7 × 10^-5"],
  },
  {
    id: "q-num-006",
    prompt: "Simplify (2^3 × 2^5) ÷ 2^4.",
    marks: 2,
    answer: "2^4|16",
    solution: "2^(3+5-4) = 2^4 = 16.",
    skillIds: ["num.indices"],
    topicId: "number",
    difficulty: 5,
    calculator: false,
    type: "short",
    commandWords: ["Simplify"],
    commonMistakes: ["Multiplying the indices"],
  },
  {
    id: "q-num-007",
    prompt: "Rationalise the denominator of 6 / √3.",
    marks: 2,
    answer: "2√3|2sqrt(3)",
    solution: "Multiply by √3/√3: 6√3 / 3 = 2√3.",
    skillIds: ["num.surds"],
    topicId: "number",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Rationalise"],
    commonMistakes: ["Leaving 6√3 / 3 unsimplified"],
  },
  {
    id: "q-num-008",
    prompt: "A length is given as 12.4 cm to 1 d.p. Find the lower and upper bounds.",
    marks: 2,
    answer: "12.35 and 12.45|12.35, 12.45",
    solution: "Error is 0.05. Lower 12.35 cm, upper 12.45 cm.",
    skillIds: ["num.bounds"],
    topicId: "number",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Using 0.1 as the error"],
  },
  {
    id: "q-num-009",
    prompt: "Find the HCF of 84 and 120.",
    marks: 2,
    answer: "12",
    solution: "84=2^2×3×7, 120=2^3×3×5. HCF=2^2×3=12.",
    skillIds: ["num.hcf-lcm", "num.prime-factors"],
    topicId: "number",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Giving the LCM instead"],
  },
  {
    id: "q-alg-001",
    prompt: "Simplify 5x + 3y − 2x + 7y.",
    marks: 1,
    answer: "3x+10y|3x + 10y",
    solution: "Collect like terms: (5x−2x)+(3y+7y)=3x+10y.",
    skillIds: ["alg.simplifying"],
    topicId: "algebra",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Simplify"],
    commonMistakes: ["Combining x and y terms"],
  },
  {
    id: "q-alg-002",
    prompt: "Expand and simplify (x + 3)(x − 2).",
    marks: 2,
    answer: "x^2+x-6|x^2 + x - 6",
    solution: "x^2 − 2x + 3x − 6 = x^2 + x − 6.",
    skillIds: ["alg.expanding"],
    topicId: "algebra",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Expand"],
    commonMistakes: ["Missing the x term", "x^2 − 6"],
  },
  {
    id: "q-alg-003",
    prompt: "Solve 3x + 5 = 20.",
    marks: 2,
    answer: "x=5|5",
    solution: "Subtract 5 from both sides: 3x = 15. Divide by 3: x = 5.",
    skillIds: ["alg.solving-linear", "alg.rearranging"],
    topicId: "algebra",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Solve"],
    commonMistakes: ["Adding 5 to 20 to get 3x = 25"],
  },
  {
    id: "q-alg-004",
    prompt: "Factorise x^2 + 5x + 6.",
    marks: 2,
    answer: "(x+2)(x+3)|(x+3)(x+2)",
    solution: "Numbers adding to 5 and multiplying to 6: 2 and 3. (x+2)(x+3).",
    skillIds: ["alg.factorising-quadratic"],
    topicId: "algebra",
    difficulty: 5,
    calculator: false,
    type: "short",
    commandWords: ["Factorise"],
    commonMistakes: ["(x+1)(x+6)"],
  },
  {
    id: "q-alg-005",
    prompt: "Solve x^2 − 5x + 6 = 0.",
    marks: 3,
    answer: "x=2 or x=3|2 and 3",
    solution: "(x−2)(x−3)=0 so x=2 or x=3.",
    skillIds: ["alg.solving-quadratic", "alg.factorising-quadratic"],
    topicId: "algebra",
    difficulty: 5,
    calculator: false,
    type: "structured",
    commandWords: ["Solve"],
    commonMistakes: ["Only giving one solution"],
  },
  {
    id: "q-alg-006",
    prompt: "Use the quadratic formula to solve x^2 + 4x − 1 = 0. Give answers to 2 d.p.",
    marks: 4,
    answer: "0.24 and -4.24|x=0.24, x=-4.24",
    solution: "x = (−4 ± √(16+4))/2 = (−4 ± √20)/2 = (−4 ± 2√5)/2 = −2 ± √5. So 0.24 and −4.24.",
    skillIds: ["alg.quadratic-formula"],
    topicId: "algebra",
    difficulty: 7,
    calculator: true,
    type: "structured",
    commandWords: ["Solve"],
    commonMistakes: ["b^2 − 4ac = 16 − 4", "Rounding to 1 d.p."],
  },
  {
    id: "q-alg-007",
    prompt: "Write x^2 + 6x − 2 in the form (x + a)^2 + b.",
    marks: 3,
    answer: "(x+3)^2-11|(x + 3)^2 − 11",
    solution: "(x+3)^2 − 9 − 2 = (x+3)^2 − 11.",
    skillIds: ["alg.completing-square"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Write"],
    commonMistakes: ["(x+6)^2", "Forgetting to subtract 9"],
  },
  {
    id: "q-alg-008",
    prompt: "Solve the simultaneous equations: 2x + y = 7 and x − y = 2.",
    marks: 3,
    answer: "x=3, y=1|x=3 y=1",
    solution: "Add: 3x = 9, x=3. Then 3 − y = 2, y=1.",
    skillIds: ["alg.simultaneous"],
    topicId: "algebra",
    difficulty: 5,
    calculator: false,
    type: "structured",
    commandWords: ["Solve"],
    commonMistakes: ["Subtracting instead of adding"],
  },
  {
    id: "q-alg-009",
    prompt: "Solve the inequality 5 − 2x > 1.",
    marks: 2,
    answer: "x<2|x < 2",
    solution: "−2x > −4. Divide by −2 and reverse: x < 2.",
    skillIds: ["alg.inequalities"],
    topicId: "algebra",
    difficulty: 5,
    calculator: false,
    type: "short",
    commandWords: ["Solve"],
    commonMistakes: ["Not reversing the inequality"],
  },
  {
    id: "q-alg-010",
    prompt: "Find the nth term of the sequence 3, 7, 11, 15, …",
    marks: 2,
    answer: "4n-1|4n − 1",
    solution: "Common difference 4, so 4n + c. When n=1, 4+c=3, c=−1. nth term 4n−1.",
    skillIds: ["alg.nth-term-linear", "alg.sequences"],
    topicId: "algebra",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["4n+3", "n+4"],
  },
  {
    id: "q-alg-011",
    prompt: "f(x) = 2x − 3. Find f(5) and f^{-1}(x).",
    marks: 3,
    answer: "7 and (x+3)/2|f(5)=7, f^{-1}(x)=(x+3)/2",
    solution: "f(5)=10−3=7. Let y=2x−3, x=(y+3)/2, so f^{-1}(x)=(x+3)/2.",
    skillIds: ["alg.functions", "alg.rearranging"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Inverse as 1/(2x−3)"],
  },
  {
    id: "q-alg-012",
    prompt: "An iterative formula is x_{n+1} = 4 / (x_n + 1) with x_0 = 1. Find x_1 and x_2.",
    marks: 2,
    answer: "x1=2, x2=4/3|2 and 1.333",
    solution: "x1 = 4/(1+1)=2. x2=4/(2+1)=4/3.",
    skillIds: ["alg.iteration"],
    topicId: "algebra",
    difficulty: 6,
    calculator: true,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Using x0 in both steps"],
  },
  {
    id: "q-alg-013",
    prompt: "Prove that the sum of two consecutive integers is always odd.",
    marks: 3,
    answer: "2n+1 which is odd",
    solution: "Let the integers be n and n+1. Sum = 2n+1, which is odd for any integer n.",
    skillIds: ["alg.proof"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "proof",
    commandWords: ["Prove"],
    commonMistakes: ["Trying examples only", "Not using algebra"],
  },
  {
    id: "q-alg-014",
    prompt: "Simplify (x^2 − 9)/(x^2 + 5x + 6).",
    marks: 3,
    answer: "(x-3)/(x+2)",
    solution: "Factor: (x−3)(x+3)/((x+2)(x+3)) = (x−3)/(x+2), x≠−3.",
    skillIds: ["alg.algebraic-fractions", "alg.factorising-quadratic"],
    topicId: "algebra",
    difficulty: 7,
    calculator: false,
    type: "structured",
    commandWords: ["Simplify"],
    commonMistakes: ["Cancelling the x^2 terms"],
  },
  {
    id: "q-geo-001",
    prompt: "A right-angled triangle has legs 5 cm and 12 cm. Find the hypotenuse.",
    marks: 2,
    answer: "13|13 cm",
    solution: "5^2 + 12^2 = 25+144=169=13^2. Hypotenuse 13 cm.",
    skillIds: ["geo.pythagoras"],
    topicId: "geometry",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["5+12=17"],
  },
  {
    id: "q-geo-002",
    prompt: "In a right-angled triangle, opposite = 7 cm and hypotenuse = 25 cm. Find the angle, to 1 d.p.",
    marks: 2,
    answer: "16.3|16.3°",
    solution: "sin θ = 7/25 = 0.28. θ = sin^{-1}(0.28) = 16.3°.",
    skillIds: ["geo.trig-right"],
    topicId: "geometry",
    difficulty: 5,
    calculator: true,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["cos^{-1}(7/25)", "Calculator in radians"],
  },
  {
    id: "q-geo-003",
    prompt: "The angle in a semicircle is 90°. A triangle is inscribed in a circle with one side as diameter 10 cm and another side 6 cm. Find the third side.",
    marks: 3,
    answer: "8|8 cm",
    solution: "The angle at the circumference standing on the diameter is 90°, so Pythagoras: 6^2 + b^2 = 10^2, b=8.",
    skillIds: ["geo.circle-theorems", "geo.pythagoras"],
    topicId: "geometry",
    difficulty: 7,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Not using the semicircle theorem"],
  },
  {
    id: "q-geo-004",
    prompt: "Vector a = (3, −1) and b = (−2, 4). Find 2a + b.",
    marks: 2,
    answer: "(4, 2)|(4,2)",
    solution: "2a = (6, −2). 2a+b = (6−2, −2+4) = (4, 2).",
    skillIds: ["geo.vectors"],
    topicId: "geometry",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Adding 2 to each component of a"],
  },
  {
    id: "q-geo-005",
    prompt: "A cuboid measures 4 cm by 3 cm by 5 cm. Find its volume and surface area.",
    marks: 3,
    answer: "volume 60, SA 94|60 and 94",
    solution: "Volume 4×3×5=60 cm³. SA = 2(4×3+4×5+3×5)=2(12+20+15)=94 cm².",
    skillIds: ["geo.volume", "geo.surface-area"],
    topicId: "geometry",
    difficulty: 4,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Forgetting to double for surface area"],
  },
  {
    id: "q-geo-006",
    prompt: "Two similar triangles have corresponding sides 4 cm and 10 cm. The smaller has area 12 cm². Find the area of the larger.",
    marks: 3,
    answer: "75|75 cm^2",
    solution: "Length scale 10/4 = 2.5. Area scale 2.5^2 = 6.25. Area = 12×6.25 = 75 cm².",
    skillIds: ["geo.similarity"],
    topicId: "geometry",
    difficulty: 6,
    calculator: true,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Multiplying area by 2.5"],
  },
  {
    id: "q-geo-007",
    prompt: "Find the interior angle of a regular octagon.",
    marks: 2,
    answer: "135|135°",
    solution: "Interior = ((8−2)×180)/8 = 1080/8 = 135°.",
    skillIds: ["geo.polygons"],
    topicId: "geometry",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Exterior 45° given as the interior"],
  },
  {
    id: "q-geo-008",
    prompt: "Triangle ABC has a=7 cm, b=9 cm, C=60°. Find side c, to 1 d.p.",
    marks: 3,
    answer: "8.2|8.2 cm",
    solution: "Cosine rule: c^2 = 7^2 + 9^2 − 2×7×9×cos60° = 49+81−63 = 67. c=√67≈8.2 cm.",
    skillIds: ["geo.trig-sine-cosine"],
    topicId: "geometry",
    difficulty: 7,
    calculator: true,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Using sine rule", "cos60=√3/2"],
  },
  {
    id: "q-rat-001",
    prompt: "A car travels 90 miles in 1 hour 30 minutes. Find its average speed in mph.",
    marks: 2,
    answer: "60|60 mph",
    solution: "1.5 hours. Speed = 90/1.5 = 60 mph.",
    skillIds: ["rat.speed", "rat.compound-measures"],
    topicId: "ratio",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["90/130", "90/1.3"],
  },
  {
    id: "q-rat-002",
    prompt: "A metal cube of volume 20 cm³ has mass 54 g. Find its density in g/cm³.",
    marks: 2,
    answer: "2.7|2.7 g/cm^3",
    solution: "Density = mass/volume = 54/20 = 2.7 g/cm³.",
    skillIds: ["rat.density"],
    topicId: "ratio",
    difficulty: 4,
    calculator: true,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Volume/mass"],
  },
  {
    id: "q-rat-003",
    prompt: "£2000 is invested at 4% compound interest per year. Find the value after 3 years, to the nearest pound.",
    marks: 3,
    answer: "2249|£2249",
    solution: "2000 × 1.04^3 = 2000 × 1.124864 = 2249.73, so £2249.",
    skillIds: ["rat.growth-decay", "num.percentages"],
    topicId: "ratio",
    difficulty: 6,
    calculator: true,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Simple interest 2000+240=2240"],
  },
  {
    id: "q-rat-004",
    prompt: "y is inversely proportional to x. When x=4, y=10. Find y when x=8.",
    marks: 3,
    answer: "5",
    solution: "y = k/x. 10 = k/4, k=40. When x=8, y=40/8=5.",
    skillIds: ["rat.inverse-proportion"],
    topicId: "ratio",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Doubling y as well"],
  },
  {
    id: "q-pro-001",
    prompt: "A fair spinner has 5 equal sections numbered 1 to 5. Find P(even).",
    marks: 1,
    answer: "2/5|0.4",
    solution: "Even numbers 2 and 4, so 2/5.",
    skillIds: ["pro.basic"],
    topicId: "probability",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["3/5"],
  },
  {
    id: "q-pro-002",
    prompt: "A bag has 4 red and 6 blue counters. Two counters are taken at random without replacement. Find P(both red).",
    marks: 3,
    answer: "2/15|0.133",
    solution: "(4/10)×(3/9)=12/90=2/15.",
    skillIds: ["pro.tree-diagrams"],
    topicId: "probability",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["(4/10)^2", "With replacement 16/100"],
  },
  {
    id: "q-pro-003",
    prompt: "P(A)=0.4, P(B)=0.5, P(A and B)=0.2. Find P(A|B).",
    marks: 2,
    answer: "0.4|2/5",
    solution: "P(A|B)=P(A and B)/P(B)=0.2/0.5=0.4.",
    skillIds: ["pro.conditional"],
    topicId: "probability",
    difficulty: 7,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["0.2/0.4=0.5"],
  },
  {
    id: "q-sta-001",
    prompt: "The numbers 4, 7, 7, 8, 14 have mean, median and mode. Find all three.",
    marks: 3,
    answer: "mean 8, median 7, mode 7|8, 7, 7",
    solution: "Mean (4+7+7+8+14)/5=8. Median is the 3rd value 7. Mode 7.",
    skillIds: ["sta.averages"],
    topicId: "statistics",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Median as mean of 7 and 8"],
  },
  {
    id: "q-sta-002",
    prompt: "A frequency table: x=1,2,3,4 with frequencies 5, 8, 4, 3. Estimate the mean.",
    marks: 3,
    answer: "2.25",
    solution: "Σfx=1×5+2×8+3×4+4×3=5+16+12+12=45. n=20. Mean=45/20=2.25.",
    skillIds: ["sta.frequency-tables"],
    topicId: "statistics",
    difficulty: 5,
    calculator: true,
    type: "structured",
    commandWords: ["Estimate", "Find"],
    commonMistakes: ["Averaging 1+2+3+4"],
  },
  {
    id: "q-sta-003",
    prompt: "A histogram has a bar from 10 to 20 with frequency density 3. Find the frequency for that class.",
    marks: 2,
    answer: "30",
    solution: "Width 10. Frequency = fd × width = 3×10=30.",
    skillIds: ["sta.histograms"],
    topicId: "statistics",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Using 3 as the frequency"],
  },
  {
    id: "q-gra-001",
    prompt: "A line has gradient 2 and y-intercept −3. Write its equation.",
    marks: 1,
    answer: "y=2x-3|y = 2x − 3",
    solution: "y = mx + c = 2x − 3.",
    skillIds: ["gra.linear"],
    topicId: "graphs",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Write"],
    commonMistakes: ["y=−3x+2"],
  },
  {
    id: "q-gra-002",
    prompt: "Sketch y = x^2 − 4x + 3, marking intercepts and the turning point.",
    marks: 4,
    answer: "intercepts (0,3),(1,0),(3,0), turning (2,-1)",
    solution: "y-intercept 3. Factor (x−1)(x−3). Vertex at x=2, y=4−8+3=−1. Minimum (2,−1).",
    skillIds: ["gra.quadratic", "alg.completing-square"],
    topicId: "graphs",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Sketch"],
    commonMistakes: ["Turning point at x=4"],
  },
  {
    id: "q-gra-003",
    prompt: "The graph of y=f(x) is translated by vector (0, 3). Write the new equation in terms of f.",
    marks: 1,
    answer: "y=f(x)+3",
    solution: "Vertical translation +3 is y = f(x)+3.",
    skillIds: ["gra.transformations"],
    topicId: "graphs",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Write"],
    commonMistakes: ["y=f(x+3)"],
  },
  {
    id: "q-alg-015",
    prompt: "Make v the subject of E = ½mv^2.",
    marks: 3,
    answer: "v=√(2E/m)|v = sqrt(2E/m)",
    solution: "2E = mv^2, v^2 = 2E/m, v = √(2E/m) (taking the positive root).",
    skillIds: ["alg.rearranging"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Make"],
    commonMistakes: ["v = 2E/m", "Forgetting the square root"],
  },
  {
    id: "q-num-010",
    prompt: "Evaluate 8^(2/3).",
    marks: 2,
    answer: "4",
    solution: "(8^(1/3))^2 = 2^2 = 4.",
    skillIds: ["num.indices"],
    topicId: "number",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Evaluate"],
    commonMistakes: ["8^(2/3)=16/3", "64"],
  },
  {
    id: "q-alg-016",
    prompt: "n is an integer. Prove that n^2 + n is always even.",
    marks: 4,
    answer: "n(n+1) is the product of consecutive integers so even",
    solution: "n^2+n = n(n+1). Consecutive integers, so one is even, product even.",
    skillIds: ["alg.proof"],
    topicId: "algebra",
    difficulty: 7,
    calculator: false,
    type: "proof",
    commandWords: ["Prove"],
    commonMistakes: ["Only checking even n"],
  },
  {
    id: "q-geo-009",
    prompt: "Angle at the centre of a circle is 110°. Find the angle at the circumference standing on the same arc.",
    marks: 2,
    answer: "55|55°",
    solution: "Angle at the circumference is half the angle at the centre: 55°.",
    skillIds: ["geo.circle-theorems"],
    topicId: "geometry",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["110°", "220°"],
  },
  {
    id: "q-geo-010",
    prompt: "Point A is (1, 2) and B is (5, 5). Find vector AB and its magnitude.",
    marks: 3,
    answer: "AB=(4,3), magnitude 5|(4,3) and 5",
    solution: "AB = (5−1, 5−2)=(4,3). |AB|=√(16+9)=5.",
    skillIds: ["geo.vectors", "geo.pythagoras"],
    topicId: "geometry",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["BA instead of AB"],
  },
  {
    id: "q-pro-004",
    prompt: "In a class of 30, 18 play football, 12 play rugby and 7 play both. How many play neither?",
    marks: 3,
    answer: "7",
    solution: "Football only 11, rugby only 5, both 7. Total 23. Neither 30−23=7.",
    skillIds: ["pro.venn"],
    topicId: "probability",
    difficulty: 5,
    calculator: false,
    type: "structured",
    commandWords: ["How many"],
    commonMistakes: ["30−18−12"],
  },
  {
    id: "q-num-011",
    prompt: "A number is rounded to 40 to 1 significant figure. What is the maximum possible value of the number?",
    marks: 1,
    answer: "45|44.999",
    solution: "Upper bound is 45 (not including 45 if strictly less than).",
    skillIds: ["num.bounds"],
    topicId: "number",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["What is"],
    commonMistakes: ["40.5", "44"],
  },
  {
    id: "q-alg-017",
    prompt: "The nth term of a quadratic sequence is n^2 + 3n + 1. Find the first three terms and the 10th term.",
    marks: 3,
    answer: "5, 11, 19 and 131",
    solution: "n=1: 5. n=2: 4+6+1=11. n=3: 9+9+1=19. n=10: 100+30+1=131.",
    skillIds: ["alg.nth-term-quadratic"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Using 3n only"],
  },
];
