import type { BankQuestion } from "@/lib/curriculum/types";

export const BANK_QUESTIONS: BankQuestion[] = [
  {
    id: "q-num-001",
    prompt: "Simplify 12/18.",
    marks: 1,
    answer: "2/3",
    solution: "Divide numerator and denominator by 6: 12÷6=2, 18÷6=3, so 2/3.",
    skillIds: ["num.fractions"],
    topicId: "number",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Simplify"],
    commonMistakes: ["Dividing only the numerator"],
  },
  {
    id: "q-num-002",
    prompt: "Work out 3/4 + 2/5.",
    marks: 2,
    answer: "23/20|1.15|1 3/20",
    solution: "Common denominator 20: 15/20 + 8/20 = 23/20.",
    skillIds: ["num.fractions"],
    topicId: "number",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Work out"],
    commonMistakes: ["Adding denominators to get 5/9"],
  },
  {
    id: "q-num-003",
    prompt: "Increase £80 by 15%.",
    marks: 2,
    answer: "92|£92",
    solution: "Multiplier 1.15. 80 × 1.15 = 92.",
    skillIds: ["num.percentages"],
    topicId: "number",
    difficulty: 4,
    calculator: true,
    type: "short",
    commandWords: ["Increase"],
    commonMistakes: ["Finding 15% and forgetting to add it"],
  },
  {
    id: "q-num-004",
    prompt: "Share £120 in the ratio 2:3:7.",
    marks: 3,
    answer: "20:30:70|£20, £30, £70",
    solution: "Parts 2+3+7=12. One part = 120/12 = 10. Amounts 20, 30, 70.",
    skillIds: ["num.ratio", "rat.ratio"],
    topicId: "ratio",
    difficulty: 4,
    calculator: false,
    type: "structured",
    commandWords: ["Share"],
    commonMistakes: ["Dividing 120 by 2, 3 and 7 separately"],
  },
  {
    id: "q-num-005",
    prompt: "Write 0.00047 in standard form.",
    marks: 1,
    answer: "4.7 × 10^-4|4.7x10^-4",
    solution: "Move the point 4 places: 4.7 × 10^-4.",
    skillIds: ["num.standard-form"],
    topicId: "number",
    difficulty: 5,
    calculator: false,
    type: "short",
    commandWords: ["Write"],
    commonMistakes: ["Positive index", "4.7 × 10^-5"],
  },
  {
    id: "q-num-006",
    prompt: "Simplify (2^3 × 2^5) ÷ 2^4.",
    marks: 2,
    answer: "2^4|16",
    solution: "2^(3+5-4) = 2^4 = 16.",
    skillIds: ["num.indices"],
    topicId: "number",
    difficulty: 5,
    calculator: false,
    type: "short",
    commandWords: ["Simplify"],
    commonMistakes: ["Multiplying the indices"],
  },
  {
    id: "q-num-007",
    prompt: "Rationalise the denominator of 6 / √3.",
    marks: 2,
    answer: "2√3|2sqrt(3)",
    solution: "Multiply by √3/√3: 6√3 / 3 = 2√3.",
    skillIds: ["num.surds"],
    topicId: "number",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Rationalise"],
    commonMistakes: ["Leaving 6√3 / 3 unsimplified"],
  },
  {
    id: "q-num-008",
    prompt: "A length is given as 12.4 cm to 1 d.p. Find the lower and upper bounds.",
    marks: 2,
    answer: "12.35 and 12.45|12.35, 12.45",
    solution: "Error is 0.05. Lower 12.35 cm, upper 12.45 cm.",
    skillIds: ["num.bounds"],
    topicId: "number",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Using 0.1 as the error"],
  },
  {
    id: "q-num-009",
    prompt: "Find the HCF of 84 and 120.",
    marks: 2,
    answer: "12",
    solution: "84=2^2×3×7, 120=2^3×3×5. HCF=2^2×3=12.",
    skillIds: ["num.hcf-lcm", "num.prime-factors"],
    topicId: "number",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Giving the LCM instead"],
  },
  {
    id: "q-alg-001",
    prompt: "Simplify 5x + 3y − 2x + 7y.",
    marks: 1,
    answer: "3x+10y|3x + 10y",
    solution: "Collect like terms: (5x−2x)+(3y+7y)=3x+10y.",
    skillIds: ["alg.simplifying"],
    topicId: "algebra",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Simplify"],
    commonMistakes: ["Combining x and y terms"],
  },
  {
    id: "q-alg-002",
    prompt: "Expand and simplify (x + 3)(x − 2).",
    marks: 2,
    answer: "x^2+x-6|x^2 + x - 6",
    solution: "x^2 − 2x + 3x − 6 = x^2 + x − 6.",
    skillIds: ["alg.expanding"],
    topicId: "algebra",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Expand"],
    commonMistakes: ["Missing the x term", "x^2 − 6"],
  },
  {
    id: "q-alg-003",
    prompt: "Solve 3x + 5 = 20.",
    marks: 2,
    answer: "x=5|5",
    solution: "Subtract 5 from both sides: 3x = 15. Divide by 3: x = 5.",
    skillIds: ["alg.solving-linear", "alg.rearranging"],
    topicId: "algebra",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Solve"],
    commonMistakes: ["Adding 5 to 20 to get 3x = 25"],
  },
  {
    id: "q-alg-004",
    prompt: "Factorise x^2 + 5x + 6.",
    marks: 2,
    answer: "(x+2)(x+3)|(x+3)(x+2)",
    solution: "Numbers adding to 5 and multiplying to 6: 2 and 3. (x+2)(x+3).",
    skillIds: ["alg.factorising-quadratic"],
    topicId: "algebra",
    difficulty: 5,
    calculator: false,
    type: "short",
    commandWords: ["Factorise"],
    commonMistakes: ["(x+1)(x+6)"],
  },
  {
    id: "q-alg-005",
    prompt: "Solve x^2 − 5x + 6 = 0.",
    marks: 3,
    answer: "x=2 or x=3|2 and 3",
    solution: "(x−2)(x−3)=0 so x=2 or x=3.",
    skillIds: ["alg.solving-quadratic", "alg.factorising-quadratic"],
    topicId: "algebra",
    difficulty: 5,
    calculator: false,
    type: "structured",
    commandWords: ["Solve"],
    commonMistakes: ["Only giving one solution"],
  },
  {
    id: "q-alg-006",
    prompt: "Use the quadratic formula to solve x^2 + 4x − 1 = 0. Give answers to 2 d.p.",
    marks: 4,
    answer: "0.24 and -4.24|x=0.24, x=-4.24",
    solution: "x = (−4 ± √(16+4))/2 = (−4 ± √20)/2 = (−4 ± 2√5)/2 = −2 ± √5. So 0.24 and −4.24.",
    skillIds: ["alg.quadratic-formula"],
    topicId: "algebra",
    difficulty: 7,
    calculator: true,
    type: "structured",
    commandWords: ["Solve"],
    commonMistakes: ["b^2 − 4ac = 16 − 4", "Rounding to 1 d.p."],
  },
  {
    id: "q-alg-007",
    prompt: "Write x^2 + 6x − 2 in the form (x + a)^2 + b.",
    marks: 3,
    answer: "(x+3)^2-11|(x + 3)^2 − 11",
    solution: "(x+3)^2 − 9 − 2 = (x+3)^2 − 11.",
    skillIds: ["alg.completing-square"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Write"],
    commonMistakes: ["(x+6)^2", "Forgetting to subtract 9"],
  },
  {
    id: "q-alg-008",
    prompt: "Solve the simultaneous equations: 2x + y = 7 and x − y = 2.",
    marks: 3,
    answer: "x=3, y=1|x=3 y=1",
    solution: "Add: 3x = 9, x=3. Then 3 − y = 2, y=1.",
    skillIds: ["alg.simultaneous"],
    topicId: "algebra",
    difficulty: 5,
    calculator: false,
    type: "structured",
    commandWords: ["Solve"],
    commonMistakes: ["Subtracting instead of adding"],
  },
  {
    id: "q-alg-009",
    prompt: "Solve the inequality 5 − 2x > 1.",
    marks: 2,
    answer: "x<2|x < 2",
    solution: "−2x > −4. Divide by −2 and reverse: x < 2.",
    skillIds: ["alg.inequalities"],
    topicId: "algebra",
    difficulty: 5,
    calculator: false,
    type: "short",
    commandWords: ["Solve"],
    commonMistakes: ["Not reversing the inequality"],
  },
  {
    id: "q-alg-010",
    prompt: "Find the nth term of the sequence 3, 7, 11, 15, …",
    marks: 2,
    answer: "4n-1|4n − 1",
    solution: "Common difference 4, so 4n + c. When n=1, 4+c=3, c=−1. nth term 4n−1.",
    skillIds: ["alg.nth-term-linear", "alg.sequences"],
    topicId: "algebra",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["4n+3", "n+4"],
  },
  {
    id: "q-alg-011",
    prompt: "f(x) = 2x − 3. Find f(5) and f^{-1}(x).",
    marks: 3,
    answer: "7 and (x+3)/2|f(5)=7, f^{-1}(x)=(x+3)/2",
    solution: "f(5)=10−3=7. Let y=2x−3, x=(y+3)/2, so f^{-1}(x)=(x+3)/2.",
    skillIds: ["alg.functions", "alg.rearranging"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Inverse as 1/(2x−3)"],
  },
  {
    id: "q-alg-012",
    prompt: "An iterative formula is x_{n+1} = 4 / (x_n + 1) with x_0 = 1. Find x_1 and x_2.",
    marks: 2,
    answer: "x1=2, x2=4/3|2 and 1.333",
    solution: "x1 = 4/(1+1)=2. x2=4/(2+1)=4/3.",
    skillIds: ["alg.iteration"],
    topicId: "algebra",
    difficulty: 6,
    calculator: true,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Using x0 in both steps"],
  },
  {
    id: "q-alg-013",
    prompt: "Prove that the sum of two consecutive integers is always odd.",
    marks: 3,
    answer: "2n+1 which is odd",
    solution: "Let the integers be n and n+1. Sum = 2n+1, which is odd for any integer n.",
    skillIds: ["alg.proof"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "proof",
    commandWords: ["Prove"],
    commonMistakes: ["Trying examples only", "Not using algebra"],
  },
  {
    id: "q-alg-014",
    prompt: "Simplify (x^2 − 9)/(x^2 + 5x + 6).",
    marks: 3,
    answer: "(x-3)/(x+2)",
    solution: "Factor: (x−3)(x+3)/((x+2)(x+3)) = (x−3)/(x+2), x≠−3.",
    skillIds: ["alg.algebraic-fractions", "alg.factorising-quadratic"],
    topicId: "algebra",
    difficulty: 7,
    calculator: false,
    type: "structured",
    commandWords: ["Simplify"],
    commonMistakes: ["Cancelling the x^2 terms"],
  },
  {
    id: "q-geo-001",
    prompt: "A right-angled triangle has legs 5 cm and 12 cm. Find the hypotenuse.",
    marks: 2,
    answer: "13|13 cm",
    solution: "5^2 + 12^2 = 25+144=169=13^2. Hypotenuse 13 cm.",
    skillIds: ["geo.pythagoras"],
    topicId: "geometry",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["5+12=17"],
  },
  {
    id: "q-geo-002",
    prompt: "In a right-angled triangle, opposite = 7 cm and hypotenuse = 25 cm. Find the angle, to 1 d.p.",
    marks: 2,
    answer: "16.3|16.3°",
    solution: "sin θ = 7/25 = 0.28. θ = sin^{-1}(0.28) = 16.3°.",
    skillIds: ["geo.trig-right"],
    topicId: "geometry",
    difficulty: 5,
    calculator: true,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["cos^{-1}(7/25)", "Calculator in radians"],
  },
  {
    id: "q-geo-003",
    prompt: "The angle in a semicircle is 90°. A triangle is inscribed in a circle with one side as diameter 10 cm and another side 6 cm. Find the third side.",
    marks: 3,
    answer: "8|8 cm",
    solution: "The angle at the circumference standing on the diameter is 90°, so Pythagoras: 6^2 + b^2 = 10^2, b=8.",
    skillIds: ["geo.circle-theorems", "geo.pythagoras"],
    topicId: "geometry",
    difficulty: 7,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Not using the semicircle theorem"],
  },
  {
    id: "q-geo-004",
    prompt: "Vector a = (3, −1) and b = (−2, 4). Find 2a + b.",
    marks: 2,
    answer: "(4, 2)|(4,2)",
    solution: "2a = (6, −2). 2a+b = (6−2, −2+4) = (4, 2).",
    skillIds: ["geo.vectors"],
    topicId: "geometry",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Adding 2 to each component of a"],
  },
  {
    id: "q-geo-005",
    prompt: "A cuboid measures 4 cm by 3 cm by 5 cm. Find its volume and surface area.",
    marks: 3,
    answer: "volume 60, SA 94|60 and 94",
    solution: "Volume 4×3×5=60 cm³. SA = 2(4×3+4×5+3×5)=2(12+20+15)=94 cm².",
    skillIds: ["geo.volume", "geo.surface-area"],
    topicId: "geometry",
    difficulty: 4,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Forgetting to double for surface area"],
  },
  {
    id: "q-geo-006",
    prompt: "Two similar triangles have corresponding sides 4 cm and 10 cm. The smaller has area 12 cm². Find the area of the larger.",
    marks: 3,
    answer: "75|75 cm^2",
    solution: "Length scale 10/4 = 2.5. Area scale 2.5^2 = 6.25. Area = 12×6.25 = 75 cm².",
    skillIds: ["geo.similarity"],
    topicId: "geometry",
    difficulty: 6,
    calculator: true,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Multiplying area by 2.5"],
  },
  {
    id: "q-geo-007",
    prompt: "Find the interior angle of a regular octagon.",
    marks: 2,
    answer: "135|135°",
    solution: "Interior = ((8−2)×180)/8 = 1080/8 = 135°.",
    skillIds: ["geo.polygons"],
    topicId: "geometry",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Exterior 45° given as the interior"],
  },
  {
    id: "q-geo-008",
    prompt: "Triangle ABC has a=7 cm, b=9 cm, C=60°. Find side c, to 1 d.p.",
    marks: 3,
    answer: "8.2|8.2 cm",
    solution: "Cosine rule: c^2 = 7^2 + 9^2 − 2×7×9×cos60° = 49+81−63 = 67. c=√67≈8.2 cm.",
    skillIds: ["geo.trig-sine-cosine"],
    topicId: "geometry",
    difficulty: 7,
    calculator: true,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Using sine rule", "cos60=√3/2"],
  },
  {
    id: "q-rat-001",
    prompt: "A car travels 90 miles in 1 hour 30 minutes. Find its average speed in mph.",
    marks: 2,
    answer: "60|60 mph",
    solution: "1.5 hours. Speed = 90/1.5 = 60 mph.",
    skillIds: ["rat.speed", "rat.compound-measures"],
    topicId: "ratio",
    difficulty: 4,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["90/130", "90/1.3"],
  },
  {
    id: "q-rat-002",
    prompt: "A metal cube of volume 20 cm³ has mass 54 g. Find its density in g/cm³.",
    marks: 2,
    answer: "2.7|2.7 g/cm^3",
    solution: "Density = mass/volume = 54/20 = 2.7 g/cm³.",
    skillIds: ["rat.density"],
    topicId: "ratio",
    difficulty: 4,
    calculator: true,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Volume/mass"],
  },
  {
    id: "q-rat-003",
    prompt: "£2000 is invested at 4% compound interest per year. Find the value after 3 years, to the nearest pound.",
    marks: 3,
    answer: "2249|£2249",
    solution: "2000 × 1.04^3 = 2000 × 1.124864 = 2249.73, so £2249.",
    skillIds: ["rat.growth-decay", "num.percentages"],
    topicId: "ratio",
    difficulty: 6,
    calculator: true,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Simple interest 2000+240=2240"],
  },
  {
    id: "q-rat-004",
    prompt: "y is inversely proportional to x. When x=4, y=10. Find y when x=8.",
    marks: 3,
    answer: "5",
    solution: "y = k/x. 10 = k/4, k=40. When x=8, y=40/8=5.",
    skillIds: ["rat.inverse-proportion"],
    topicId: "ratio",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Doubling y as well"],
  },
  {
    id: "q-pro-001",
    prompt: "A fair spinner has 5 equal sections numbered 1 to 5. Find P(even).",
    marks: 1,
    answer: "2/5|0.4",
    solution: "Even numbers 2 and 4, so 2/5.",
    skillIds: ["pro.basic"],
    topicId: "probability",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["3/5"],
  },
  {
    id: "q-pro-002",
    prompt: "A bag has 4 red and 6 blue counters. Two counters are taken at random without replacement. Find P(both red).",
    marks: 3,
    answer: "2/15|0.133",
    solution: "(4/10)×(3/9)=12/90=2/15.",
    skillIds: ["pro.tree-diagrams"],
    topicId: "probability",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["(4/10)^2", "With replacement 16/100"],
  },
  {
    id: "q-pro-003",
    prompt: "P(A)=0.4, P(B)=0.5, P(A and B)=0.2. Find P(A|B).",
    marks: 2,
    answer: "0.4|2/5",
    solution: "P(A|B)=P(A and B)/P(B)=0.2/0.5=0.4.",
    skillIds: ["pro.conditional"],
    topicId: "probability",
    difficulty: 7,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["0.2/0.4=0.5"],
  },
  {
    id: "q-sta-001",
    prompt: "The numbers 4, 7, 7, 8, 14 have mean, median and mode. Find all three.",
    marks: 3,
    answer: "mean 8, median 7, mode 7|8, 7, 7",
    solution: "Mean (4+7+7+8+14)/5=8. Median is the 3rd value 7. Mode 7.",
    skillIds: ["sta.averages"],
    topicId: "statistics",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Median as mean of 7 and 8"],
  },
  {
    id: "q-sta-002",
    prompt: "A frequency table: x=1,2,3,4 with frequencies 5, 8, 4, 3. Estimate the mean.",
    marks: 3,
    answer: "2.25",
    solution: "Σfx=1×5+2×8+3×4+4×3=5+16+12+12=45. n=20. Mean=45/20=2.25.",
    skillIds: ["sta.frequency-tables"],
    topicId: "statistics",
    difficulty: 5,
    calculator: true,
    type: "structured",
    commandWords: ["Estimate", "Find"],
    commonMistakes: ["Averaging 1+2+3+4"],
  },
  {
    id: "q-sta-003",
    prompt: "A histogram has a bar from 10 to 20 with frequency density 3. Find the frequency for that class.",
    marks: 2,
    answer: "30",
    solution: "Width 10. Frequency = fd × width = 3×10=30.",
    skillIds: ["sta.histograms"],
    topicId: "statistics",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["Using 3 as the frequency"],
  },
  {
    id: "q-gra-001",
    prompt: "A line has gradient 2 and y-intercept −3. Write its equation.",
    marks: 1,
    answer: "y=2x-3|y = 2x − 3",
    solution: "y = mx + c = 2x − 3.",
    skillIds: ["gra.linear"],
    topicId: "graphs",
    difficulty: 3,
    calculator: false,
    type: "short",
    commandWords: ["Write"],
    commonMistakes: ["y=−3x+2"],
  },
  {
    id: "q-gra-002",
    prompt: "Sketch y = x^2 − 4x + 3, marking intercepts and the turning point.",
    marks: 4,
    answer: "intercepts (0,3),(1,0),(3,0), turning (2,-1)",
    solution: "y-intercept 3. Factor (x−1)(x−3). Vertex at x=2, y=4−8+3=−1. Minimum (2,−1).",
    skillIds: ["gra.quadratic", "alg.completing-square"],
    topicId: "graphs",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Sketch"],
    commonMistakes: ["Turning point at x=4"],
  },
  {
    id: "q-gra-003",
    prompt: "The graph of y=f(x) is translated by vector (0, 3). Write the new equation in terms of f.",
    marks: 1,
    answer: "y=f(x)+3",
    solution: "Vertical translation +3 is y = f(x)+3.",
    skillIds: ["gra.transformations"],
    topicId: "graphs",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Write"],
    commonMistakes: ["y=f(x+3)"],
  },
  {
    id: "q-alg-015",
    prompt: "Make v the subject of E = ½mv^2.",
    marks: 3,
    answer: "v=√(2E/m)|v = sqrt(2E/m)",
    solution: "2E = mv^2, v^2 = 2E/m, v = √(2E/m) (taking the positive root).",
    skillIds: ["alg.rearranging"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Make"],
    commonMistakes: ["v = 2E/m", "Forgetting the square root"],
  },
  {
    id: "q-num-010",
    prompt: "Evaluate 8^(2/3).",
    marks: 2,
    answer: "4",
    solution: "(8^(1/3))^2 = 2^2 = 4.",
    skillIds: ["num.indices"],
    topicId: "number",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Evaluate"],
    commonMistakes: ["8^(2/3)=16/3", "64"],
  },
  {
    id: "q-alg-016",
    prompt: "n is an integer. Prove that n^2 + n is always even.",
    marks: 4,
    answer: "n(n+1) is the product of consecutive integers so even",
    solution: "n^2+n = n(n+1). Consecutive integers, so one is even, product even.",
    skillIds: ["alg.proof"],
    topicId: "algebra",
    difficulty: 7,
    calculator: false,
    type: "proof",
    commandWords: ["Prove"],
    commonMistakes: ["Only checking even n"],
  },
  {
    id: "q-geo-009",
    prompt: "Angle at the centre of a circle is 110°. Find the angle at the circumference standing on the same arc.",
    marks: 2,
    answer: "55|55°",
    solution: "Angle at the circumference is half the angle at the centre: 55°.",
    skillIds: ["geo.circle-theorems"],
    topicId: "geometry",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["Find"],
    commonMistakes: ["110°", "220°"],
  },
  {
    id: "q-geo-010",
    prompt: "Point A is (1, 2) and B is (5, 5). Find vector AB and its magnitude.",
    marks: 3,
    answer: "AB=(4,3), magnitude 5|(4,3) and 5",
    solution: "AB = (5−1, 5−2)=(4,3). |AB|=√(16+9)=5.",
    skillIds: ["geo.vectors", "geo.pythagoras"],
    topicId: "geometry",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["BA instead of AB"],
  },
  {
    id: "q-pro-004",
    prompt: "In a class of 30, 18 play football, 12 play rugby and 7 play both. How many play neither?",
    marks: 3,
    answer: "7",
    solution: "Football only 11, rugby only 5, both 7. Total 23. Neither 30−23=7.",
    skillIds: ["pro.venn"],
    topicId: "probability",
    difficulty: 5,
    calculator: false,
    type: "structured",
    commandWords: ["How many"],
    commonMistakes: ["30−18−12"],
  },
  {
    id: "q-num-011",
    prompt: "A number is rounded to 40 to 1 significant figure. What is the maximum possible value of the number?",
    marks: 1,
    answer: "45|44.999",
    solution: "Upper bound is 45 (not including 45 if strictly less than).",
    skillIds: ["num.bounds"],
    topicId: "number",
    difficulty: 6,
    calculator: false,
    type: "short",
    commandWords: ["What is"],
    commonMistakes: ["40.5", "44"],
  },
  {
    id: "q-alg-017",
    prompt: "The nth term of a quadratic sequence is n^2 + 3n + 1. Find the first three terms and the 10th term.",
    marks: 3,
    answer: "5, 11, 19 and 131",
    solution: "n=1: 5. n=2: 4+6+1=11. n=3: 9+9+1=19. n=10: 100+30+1=131.",
    skillIds: ["alg.nth-term-quadratic"],
    topicId: "algebra",
    difficulty: 6,
    calculator: false,
    type: "structured",
    commandWords: ["Find"],
    commonMistakes: ["Using 3n only"],
  },
  // Additional calibrated GCSE questions. Each strand includes a deliberate
  // progression from secure method to higher-tier application and proof.
  {
    id: "q-num-012", prompt: "Work out -7 + 12 - 9.", marks: 1, answer: "-4",
    solution: "-7 + 12 = 5, then 5 - 9 = -4.", skillIds: ["num.negatives", "num.order-ops"], topicId: "number", difficulty: 3, calculator: false, type: "short", commandWords: ["Work out"], commonMistakes: ["Treating -7 + 12 as -19"],
  },
  {
    id: "q-num-013", prompt: "Write 0.375 as a fraction in its simplest form.", marks: 2, answer: "3/8",
    solution: "0.375 = 375/1000. Divide top and bottom by 125 to get 3/8.", skillIds: ["num.decimals", "num.fdp", "num.fractions"], topicId: "number", difficulty: 4, calculator: false, type: "short", commandWords: ["Write"], commonMistakes: ["Writing 375/100"],
  },
  {
    id: "q-num-014", prompt: "A jacket costs £68 after a 15% discount. Find its original price.", marks: 3, answer: "80|£80",
    solution: "After a 15% discount, 85% remains. Original price = 68 / 0.85 = 80.", skillIds: ["num.reverse-percentages", "num.percentages"], topicId: "number", difficulty: 6, calculator: true, type: "structured", commandWords: ["Find"], commonMistakes: ["Taking 15% of 68"],
  },
  {
    id: "q-num-015", prompt: "Convert 0.1̇6̇ (0.1666...) to a fraction in its simplest form.", marks: 3, answer: "1/6",
    solution: "Let x=0.1666... Then 10x=1.666... and 100x=16.666.... Subtract to get 90x=15, so x=1/6.", skillIds: ["num.recurring-decimals"], topicId: "number", difficulty: 6, calculator: false, type: "structured", commandWords: ["Convert"], commonMistakes: ["Using 1/9"],
  },
  {
    id: "q-num-016", prompt: "The mass of a parcel is 2.4 kg, correct to the nearest 0.1 kg. Find the upper bound for its density if its volume is 0.30 m³, correct to the nearest 0.01 m³.", marks: 4, answer: "8.275862...|8.28",
    solution: "For maximum density use maximum mass and minimum volume: 2.45 / 0.295 = 8.275862..., so 8.28 kg/m³ to 3 s.f.", skillIds: ["num.error-intervals", "num.bounds"], topicId: "number", difficulty: 8, calculator: true, type: "structured", commandWords: ["Find"], commonMistakes: ["Using both upper bounds"],
  },
  {
    id: "q-num-017", prompt: "Estimate the value of (19.8 × 0.49) / 4.1.", marks: 2, answer: "2.5|about 2.5",
    solution: "Use 20 × 0.5 / 4 = 10/4 = 2.5.", skillIds: ["num.estimation"], topicId: "number", difficulty: 4, calculator: false, type: "short", commandWords: ["Estimate"], commonMistakes: ["Trying to calculate exactly"],
  },
  {
    id: "q-alg-018", prompt: "Expand and simplify (2x - 3)(x + 4).", marks: 2, answer: "2x^2+5x-12|2x^2 + 5x - 12",
    solution: "2x² + 8x - 3x - 12 = 2x² + 5x - 12.", skillIds: ["alg.expanding-double"], topicId: "algebra", difficulty: 4, calculator: false, type: "short", commandWords: ["Expand"], commonMistakes: ["Missing the middle terms"],
  },
  {
    id: "q-alg-019", prompt: "Factorise fully 6x² - 15x.", marks: 2, answer: "3x(2x-5)|3x(2x - 5)",
    solution: "The highest common factor is 3x, leaving 2x - 5.", skillIds: ["alg.factorising-linear"], topicId: "algebra", difficulty: 4, calculator: false, type: "short", commandWords: ["Factorise"], commonMistakes: ["Factoring out 3 only"],
  },
  {
    id: "q-alg-020", prompt: "Find the equation of the line through (2, 5) and (6, 13).", marks: 3, answer: "y=2x+1|y = 2x + 1",
    solution: "Gradient=(13-5)/(6-2)=2. Using (2,5): 5=4+c, so c=1.", skillIds: ["alg.equation-of-line"], topicId: "algebra", difficulty: 5, calculator: false, type: "structured", commandWords: ["Find"], commonMistakes: ["Using 5 as the intercept"],
  },
  {
    id: "q-alg-021", prompt: "The line y = -3x + 7 is perpendicular to a line through (4, 1). Find the equation of the perpendicular line.", marks: 3, answer: "y=1/3x-1/3|y = (1/3)x - 1/3",
    solution: "A perpendicular gradient is 1/3. Using (4,1): 1=4/3+c, so c=-1/3.", skillIds: ["alg.parallel-perpendicular"], topicId: "algebra", difficulty: 7, calculator: false, type: "structured", commandWords: ["Find"], commonMistakes: ["Using gradient -1/3"],
  },
  {
    id: "q-alg-022", prompt: "Solve x² - x - 6 > 0.", marks: 3, answer: "x<-2 or x>3|x < -2 or x > 3",
    solution: "(x-3)(x+2)>0. The product is positive outside the roots, so x<-2 or x>3.", skillIds: ["alg.quadratic-inequalities", "alg.factorising-quadratic"], topicId: "algebra", difficulty: 8, calculator: false, type: "structured", commandWords: ["Solve"], commonMistakes: ["Giving -2 < x < 3"],
  },
  {
    id: "q-alg-023", prompt: "Prove that (n + 1)² - (n - 1)² is divisible by 4 for every integer n.", marks: 4, answer: "4n",
    solution: "Expand: n²+2n+1 - (n²-2n+1) = 4n. Since n is an integer, 4n is divisible by 4.", skillIds: ["alg.identities", "alg.proof"], topicId: "algebra", difficulty: 8, calculator: false, type: "proof", commandWords: ["Prove"], commonMistakes: ["Only checking one value of n"],
  },
  {
    id: "q-rat-005", prompt: "A recipe for 6 people uses 450 g of flour. How much flour is needed for 14 people?", marks: 2, answer: "1050|1050g|1050 g",
    solution: "450 ÷ 6 = 75 g per person. 75 × 14 = 1050 g.", skillIds: ["rat.recipes", "num.ratio"], topicId: "ratio", difficulty: 3, calculator: false, type: "short", commandWords: ["How much"], commonMistakes: ["Multiplying 450 by 14"],
  },
  {
    id: "q-rat-006", prompt: "On a map with scale 1:25 000, two towns are 7.6 cm apart. Find the real distance in km.", marks: 3, answer: "1.9|1.9km|1.9 km",
    solution: "7.6 × 25 000 = 190 000 cm = 1.9 km.", skillIds: ["rat.scale-drawings"], topicId: "ratio", difficulty: 5, calculator: true, type: "structured", commandWords: ["Find"], commonMistakes: ["Giving 190 km"],
  },
  {
    id: "q-rat-007", prompt: "y is directly proportional to x². When x=3, y=45. Find y when x=5.", marks: 3, answer: "125",
    solution: "y=kx². 45=9k, so k=5. When x=5, y=5×25=125.", skillIds: ["rat.direct-proportion"], topicId: "ratio", difficulty: 6, calculator: false, type: "structured", commandWords: ["Find"], commonMistakes: ["Using y=15x"],
  },
  {
    id: "q-rat-008", prompt: "A force of 720 N acts on an area of 0.18 m². Calculate the pressure.", marks: 2, answer: "4000|4000Pa|4000 Pa",
    solution: "Pressure = force ÷ area = 720 ÷ 0.18 = 4000 Pa.", skillIds: ["rat.pressure"], topicId: "ratio", difficulty: 5, calculator: true, type: "short", commandWords: ["Calculate"], commonMistakes: ["Multiplying force by area"],
  },
  {
    id: "q-rat-009", prompt: "£300 is exchanged for euros at £1 = €1.16. The euros are changed back at £1 = €1.20. How many pounds are received?", marks: 3, answer: "290|£290",
    solution: "€300×1.16 = €348. At €1.20 per £, pounds = 348 ÷ 1.20 = 290.", skillIds: ["rat.currency"], topicId: "ratio", difficulty: 6, calculator: true, type: "structured", commandWords: ["How many"], commonMistakes: ["Multiplying by 1.20 on the return"],
  },
  {
    id: "q-rat-010", prompt: "Pack A has 750 g of cereal for £2.70. Pack B has 1.2 kg for £4.08. Which is the better buy?", marks: 3, answer: "Pack B|B",
    solution: "A: £2.70 ÷ 0.75 = £3.60/kg. B: £4.08 ÷ 1.2 = £3.40/kg, so B is the better buy.", skillIds: ["rat.best-buys"], topicId: "ratio", difficulty: 5, calculator: true, type: "structured", commandWords: ["Which"], commonMistakes: ["Comparing packet prices only"],
  },
  {
    id: "q-geo-011", prompt: "Two angles of a triangle are 48° and 67°. Find the third angle.", marks: 1, answer: "65|65°",
    solution: "Angles in a triangle total 180°. 180 - 48 - 67 = 65°.", skillIds: ["geo.angles"], topicId: "geometry", difficulty: 3, calculator: false, type: "short", commandWords: ["Find"], commonMistakes: ["Adding the angles"],
  },
  {
    id: "q-geo-012", prompt: "Calculate the area of a trapezium with parallel sides 8 cm and 14 cm and height 6 cm.", marks: 2, answer: "66|66cm^2|66 cm²",
    solution: "Area = ½(8+14)×6 = 66 cm².", skillIds: ["geo.area"], topicId: "geometry", difficulty: 4, calculator: false, type: "short", commandWords: ["Calculate"], commonMistakes: ["Using 8×14×6"],
  },
  {
    id: "q-geo-013", prompt: "A ship travels on a bearing of 135° from A. State the bearing of A from the ship.", marks: 2, answer: "315|315°",
    solution: "Reverse bearings differ by 180°. 135 + 180 = 315°.", skillIds: ["geo.bearings"], topicId: "geometry", difficulty: 5, calculator: false, type: "short", commandWords: ["State"], commonMistakes: ["Giving 045°"],
  },
  {
    id: "q-geo-014", prompt: "A cone has radius 3 cm and vertical height 8 cm. Calculate its volume in terms of π.", marks: 3, answer: "24π|24pi|24 π",
    solution: "Volume = (1/3)πr²h = (1/3)π×9×8 = 24π cm³.", skillIds: ["geo.cones-spheres", "geo.volume"], topicId: "geometry", difficulty: 6, calculator: false, type: "structured", commandWords: ["Calculate"], commonMistakes: ["Using πr²h without dividing by 3"],
  },
  {
    id: "q-geo-015", prompt: "Two similar solids have length scale factor 3. The smaller solid has volume 40 cm³. Find the volume of the larger solid.", marks: 3, answer: "1080|1080cm^3|1080 cm³",
    solution: "Volume scale factor = 3³ = 27. 40×27 = 1080 cm³.", skillIds: ["geo.similar-area-volume", "geo.similarity"], topicId: "geometry", difficulty: 7, calculator: false, type: "structured", commandWords: ["Find"], commonMistakes: ["Multiplying by 3"],
  },
  {
    id: "q-geo-016", prompt: "In triangle ABC, a=7, b=10 and angle C=48°. Calculate the area of the triangle to 1 d.p.", marks: 3, answer: "26.0|26cm^2|26.0cm^2",
    solution: "Area = ½ab sin C = ½×7×10×sin48° = 26.0 cm² to 1 d.p.", skillIds: ["geo.triangle-area-trig"], topicId: "geometry", difficulty: 7, calculator: true, type: "structured", commandWords: ["Calculate"], commonMistakes: ["Using cos 48°"],
  },
  {
    id: "q-pro-005", prompt: "A bag has 5 red, 3 blue and 2 green counters. Find P(blue or green).", marks: 1, answer: "1/2|0.5",
    solution: "There are 3+2=5 blue or green counters out of 10, so 5/10=1/2.", skillIds: ["pro.sample-spaces", "pro.basic"], topicId: "probability", difficulty: 3, calculator: false, type: "short", commandWords: ["Find"], commonMistakes: ["Adding 3/10 and 2/10 incorrectly"],
  },
  {
    id: "q-pro-006", prompt: "Of 120 bulbs tested, 9 are faulty. Estimate how many faulty bulbs there will be in a batch of 800.", marks: 2, answer: "60",
    solution: "Relative frequency = 9/120 = 0.075. 0.075×800 = 60.", skillIds: ["pro.relative-frequency"], topicId: "probability", difficulty: 4, calculator: false, type: "short", commandWords: ["Estimate"], commonMistakes: ["Using 9/800"],
  },
  {
    id: "q-pro-007", prompt: "A spinner has P(red)=0.4. It is spun twice. Find P(red both times).", marks: 2, answer: "0.16|16/100|4/25",
    solution: "The spins are independent, so 0.4×0.4=0.16.", skillIds: ["pro.independent"], topicId: "probability", difficulty: 5, calculator: false, type: "short", commandWords: ["Find"], commonMistakes: ["Adding 0.4 + 0.4"],
  },
  {
    id: "q-pro-008", prompt: "Complete a frequency tree: 80 students; 46 study French; 21 of the French students also study Spanish; 18 students study neither. How many study Spanish only?", marks: 3, answer: "16",
    solution: "Students studying at least one = 80-18=62. French only = 46-21=25. Spanish only = 62-25-21=16.", skillIds: ["pro.frequency-trees"], topicId: "probability", difficulty: 6, calculator: false, type: "structured", commandWords: ["How many"], commonMistakes: ["Forgetting to remove neither"],
  },
  {
    id: "q-pro-009", prompt: "Two fair six-sided dice are rolled. Find the probability that the total is greater than 9.", marks: 3, answer: "1/6|6/36",
    solution: "Totals greater than 9 are 10 (3 ways), 11 (2 ways), 12 (1 way): 6 of 36, so 1/6.", skillIds: ["pro.sample-spaces"], topicId: "probability", difficulty: 6, calculator: false, type: "structured", commandWords: ["Find"], commonMistakes: ["Counting 9 as greater than 9"],
  },
  {
    id: "q-pro-010", prompt: "A biased coin has P(head)=p. It is tossed twice. Given that the probability of two heads is 0.49, find p.", marks: 2, answer: "0.7",
    solution: "p²=0.49, so p=0.7 because a probability is non-negative.", skillIds: ["pro.independent"], topicId: "probability", difficulty: 7, calculator: false, type: "structured", commandWords: ["Find"], commonMistakes: ["Giving ±0.7"],
  },
  {
    id: "q-sta-004", prompt: "The values are 4, 7, 7, 9, 13. Find the median and the range.", marks: 2, answer: "median 7, range 9|7 and 9",
    solution: "The middle value is 7. Range = 13-4=9.", skillIds: ["sta.averages"], topicId: "statistics", difficulty: 3, calculator: false, type: "short", commandWords: ["Find"], commonMistakes: ["Using the mean for median"],
  },
  {
    id: "q-sta-005", prompt: "A class has 12 boys and 18 girls. A stratified sample of 15 is taken. How many girls should be selected?", marks: 2, answer: "9",
    solution: "Girls: 18/30 × 15 = 9.", skillIds: ["sta.stratified", "sta.sampling"], topicId: "statistics", difficulty: 4, calculator: false, type: "short", commandWords: ["How many"], commonMistakes: ["Taking half of 15"],
  },
  {
    id: "q-sta-006", prompt: "The grouped table has intervals 0<x≤10 (frequency 4), 10<x≤20 (frequency 7), 20<x≤30 (frequency 9). Estimate the mean.", marks: 3, answer: "17.5",
    solution: "Use midpoints 5,15,25. Sum fx=20+105+225=350; total f=20; estimate=350/20=17.5.", skillIds: ["sta.grouped-data"], topicId: "statistics", difficulty: 5, calculator: false, type: "structured", commandWords: ["Estimate"], commonMistakes: ["Using class boundaries instead of midpoints"],
  },
  {
    id: "q-sta-007", prompt: "The lower quartile of a data set is 12 and the upper quartile is 27. Find the interquartile range.", marks: 1, answer: "15",
    solution: "IQR = upper quartile - lower quartile = 27-12=15.", skillIds: ["sta.box-plots"], topicId: "statistics", difficulty: 5, calculator: false, type: "short", commandWords: ["Find"], commonMistakes: ["Adding the quartiles"],
  },
  {
    id: "q-sta-008", prompt: "On a cumulative frequency graph, the total frequency is 80. The readings at the lower and upper quartiles are 23 and 51. Estimate the interquartile range.", marks: 3, answer: "28",
    solution: "Lower quartile is at cumulative frequency 20 and upper quartile at 60. IQR=51-23=28.", skillIds: ["sta.cumulative-frequency"], topicId: "statistics", difficulty: 6, calculator: false, type: "structured", commandWords: ["Estimate"], commonMistakes: ["Using 40 and 80 for quartiles"],
  },
  {
    id: "q-sta-009", prompt: "In a capture-recapture study, 40 fish are marked and released. Later 50 fish are caught and 10 are marked. Estimate the fish population.", marks: 3, answer: "200",
    solution: "40/N = 10/50, so 10N=2000 and N=200.", skillIds: ["sta.capture-recapture"], topicId: "statistics", difficulty: 6, calculator: false, type: "structured", commandWords: ["Estimate"], commonMistakes: ["Adding 40 and 50"],
  },
  {
    id: "q-gra-004", prompt: "For y = 2x³ - 3x, find y when x=-2.", marks: 2, answer: "-10",
    solution: "2(-2)³ - 3(-2) = -16 + 6 = -10.", skillIds: ["gra.cubic"], topicId: "graphs", difficulty: 4, calculator: false, type: "short", commandWords: ["Find"], commonMistakes: ["-16-6"],
  },
  {
    id: "q-gra-005", prompt: "The graph y=3/x passes through a point with x=-6. Find its y-coordinate.", marks: 1, answer: "-1/2|-0.5",
    solution: "y=3/-6=-1/2.", skillIds: ["gra.reciprocal"], topicId: "graphs", difficulty: 4, calculator: false, type: "short", commandWords: ["Find"], commonMistakes: ["1/2"],
  },
  {
    id: "q-gra-006", prompt: "The population of bacteria is modelled by P=500×1.08^t. Find P when t=3, to the nearest whole number.", marks: 2, answer: "630|630",
    solution: "P=500×1.08³=629.856, so 630.", skillIds: ["gra.exponential"], topicId: "graphs", difficulty: 5, calculator: true, type: "short", commandWords: ["Find"], commonMistakes: ["500×1.24"],
  },
  {
    id: "q-gra-007", prompt: "A velocity-time graph shows a constant velocity of 12 m/s for 25 seconds. Find the distance travelled.", marks: 2, answer: "300|300m|300 m",
    solution: "Distance is the area under the graph: 12×25=300 m.", skillIds: ["gra.velocity-time", "gra.area-under"], topicId: "graphs", difficulty: 5, calculator: false, type: "short", commandWords: ["Find"], commonMistakes: ["Giving 12 m/s"],
  },
  {
    id: "q-gra-008", prompt: "Solve x² - x - 2 = 0 graphically. Give the x-values where y=x²-x-2 crosses the x-axis.", marks: 2, answer: "-1 and 2|x=-1, x=2",
    solution: "The roots are the x-intercepts. x²-x-2=(x-2)(x+1), so x=-1 and x=2.", skillIds: ["gra.solving-graphically", "gra.quadratic"], topicId: "graphs", difficulty: 6, calculator: false, type: "structured", commandWords: ["Solve"], commonMistakes: ["Giving the y-intercept -2"],
  },
  {
    id: "q-gra-009", prompt: "State the period of y=sin x for 0°≤x≤360°, and give y when x=90°.", marks: 2, answer: "360 and 1|360°, 1",
    solution: "The sine graph repeats every 360°, and sin90°=1.", skillIds: ["gra.trig-graphs", "geo.exact-trig"], topicId: "graphs", difficulty: 7, calculator: false, type: "short", commandWords: ["State"], commonMistakes: ["Period 180°"],
  },
];
