/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as Grade9RouteImport } from './routes/grade-9'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarkerRouteImport } from './routes/marker'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as ExamIdRouteImport } from './routes/exam.$id'
import { Route as MarkerIdRouteImport } from './routes/marker.$id'
import { Route as QIdRouteImport } from './routes/q.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const Grade9Route = Grade9RouteImport.update({
  id: '/grade-9',
  path: '/grade-9',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkerRoute = MarkerRouteImport.update({
  id: '/marker',
  path: '/marker',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIdRoute = ExamIdRouteImport.update({
  id: '/exam/$id',
  path: '/exam/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkerIdRoute = MarkerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarkerRoute,
} as any)
const QIdRoute = QIdRouteImport.update({
  id: '/q/$id',
  path: '/q/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/grade-9': typeof Grade9Route
  '/login': typeof LoginRoute
  '/marker': typeof MarkerRouteWithChildren
  '/mistakes': typeof MistakesRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/tests': typeof TestsRoute
  '/weekly': typeof WeeklyRoute
  '/exam/$id': typeof ExamIdRoute
  '/marker/$id': typeof MarkerIdRoute
  '/q/$id': typeof QIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/grade-9': typeof Grade9Route
  '/login': typeof LoginRoute
  '/marker': typeof MarkerRouteWithChildren
  '/mistakes': typeof MistakesRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/tests': typeof TestsRoute
  '/weekly': typeof WeeklyRoute
  '/exam/$id': typeof ExamIdRoute
  '/marker/$id': typeof MarkerIdRoute
  '/q/$id': typeof QIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/grade-9': typeof Grade9Route
  '/login': typeof LoginRoute
  '/marker': typeof MarkerRouteWithChildren
  '/mistakes': typeof MistakesRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/tests': typeof TestsRoute
  '/weekly': typeof WeeklyRoute
  '/exam/$id': typeof ExamIdRoute
  '/marker/$id': typeof MarkerIdRoute
  '/q/$id': typeof QIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/grade-9'
    | '/login'
    | '/marker'
    | '/mistakes'
    | '/plan'
    | '/practice'
    | '/progress'
    | '/settings'
    | '/tests'
    | '/weekly'
    | '/exam/$id'
    | '/marker/$id'
    | '/q/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/grade-9'
    | '/login'
    | '/marker'
    | '/mistakes'
    | '/plan'
    | '/practice'
    | '/progress'
    | '/settings'
    | '/tests'
    | '/weekly'
    | '/exam/$id'
    | '/marker/$id'
    | '/q/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/grade-9'
    | '/login'
    | '/marker'
    | '/mistakes'
    | '/plan'
    | '/practice'
    | '/progress'
    | '/settings'
    | '/tests'
    | '/weekly'
    | '/exam/$id'
    | '/marker/$id'
    | '/q/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  Grade9Route: typeof Grade9Route
  LoginRoute: typeof LoginRoute
  MarkerRoute: typeof MarkerRouteWithChildren
  MistakesRoute: typeof MistakesRoute
  PlanRoute: typeof PlanRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  TestsRoute: typeof TestsRoute
  WeeklyRoute: typeof WeeklyRoute
  ExamIdRoute: typeof ExamIdRoute
  QIdRoute: typeof QIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-9': {
      id: '/grade-9'
      path: '/grade-9'
      fullPath: '/grade-9'
      preLoaderRoute: typeof Grade9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marker': {
      id: '/marker'
      path: '/marker'
      fullPath: '/marker'
      preLoaderRoute: typeof MarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$id': {
      id: '/exam/$id'
      path: '/exam/$id'
      fullPath: '/exam/$id'
      preLoaderRoute: typeof ExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marker/$id': {
      id: '/marker/$id'
      path: '/$id'
      fullPath: '/marker/$id'
      preLoaderRoute: typeof MarkerIdRouteImport
      parentRoute: typeof MarkerRoute
    }
    '/q/$id': {
      id: '/q/$id'
      path: '/q/$id'
      fullPath: '/q/$id'
      preLoaderRoute: typeof QIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarkerRouteChildren {
  MarkerIdRoute: typeof MarkerIdRoute
}

const MarkerRouteChildren: MarkerRouteChildren = {
  MarkerIdRoute: MarkerIdRoute,
}

const MarkerRouteWithChildren =
  MarkerRoute._addFileChildren(MarkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  Grade9Route: Grade9Route,
  LoginRoute: LoginRoute,
  MarkerRoute: MarkerRouteWithChildren,
  MistakesRoute: MistakesRoute,
  PlanRoute: PlanRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  TestsRoute: TestsRoute,
  WeeklyRoute: WeeklyRoute,
  ExamIdRoute: ExamIdRoute,
  QIdRoute: QIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
